---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  channel: {{ .Values.channel }}
  installPlanApproval: Manual
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
