images:
  - name: rhaiis
    image: registry.redhat.io/rhaiis/vllm-cuda-rhel9:3.2.4
  - name: llama-31-8b
    image: registry.redhat.io/rhelai1/modelcar-llama-3-1-8b-instruct-fp8-dynamic:1.5
  - name: guidellm
    image: ghcr.io/vllm-project/guidellm:v0.4.0
  - name: multiturn-benchmark
    image: quay.io/hayesphilip/multi-turn-benchmark:0.0.1
