apiVersion: v1
kind: Namespace
metadata:
  name: llm-d-project
  labels:
    opendatahub.io/dashboard: "true"
  annotations:
    openshift.io/description: Project for llm-d lab resources
    openshift.io/display-name: llm-d Project
