apiVersion: infrastructure.opendatahub.io/v1
kind: HardwareProfile
metadata:
  annotations:
    opendatahub.io/dashboard-feature-visibility: '[]'
    opendatahub.io/description: Provides a baseline hardware profile for the llm-d lab
    opendatahub.io/disabled: "false"
    opendatahub.io/display-name: Default Profile
    opendatahub.io/managed: "false"
  labels:
    app.kubernetes.io/part-of: hardwareprofile
    app.opendatahub.io/hardwareprofile: "true"
  name: default-profile
  namespace: redhat-ods-applications
spec:
  identifiers:
  - defaultCount: 8
    displayName: CPU
    identifier: cpu
    maxCount: 32
    minCount: 1
    resourceType: CPU
  - defaultCount: 16Gi
    displayName: Memory
    identifier: memory
    maxCount: 128Gi
    minCount: 2Gi
    resourceType: Memory
  - defaultCount: 1
    displayName: NVIDIA L4
    identifier: nvidia.com/gpu
    maxCount: 4
    minCount: 0
    resourceType: Accelerator
