{{- if and .Values.llmD.namespace.create .Values.llmD.namespace.scrape }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llm-d-router-metrics
  namespace: llm-d-project
  labels:
    monitoring.opendatahub.io/scrape: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: llminferenceservice-router-scheduler
  namespaceSelector: {}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llm-d-pool-metrics
  namespace: llm-d-project
  labels:
    monitoring.opendatahub.io/scrape: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: llminferenceservice-workload
  namespaceSelector: {}
  endpoints:
    - port: https
      path: /metrics
      interval: 30s
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
{{- end }}
