apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-puller
spec:
  selector:
    matchLabels:
      app: image-puller
  template:
    metadata:
      labels:
        app: image-puller
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
      containers:
      {{- range .Values.images }}
      - name: pull-{{ .name }}
        image: {{ .image }}
        command:
        - /bin/sleep
        args:
        - infinity
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      {{- end }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
