apiVersion: v1
kind: ServiceAccount
metadata:
  name: fix-gpu-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fix-gpu-operator
subjects:
- kind: ServiceAccount
  name: fix-gpu-operator
  namespace: nvidia-gpu-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
